=== Hamza-Kouki/XML-TPS-/examens/elyessTps/TP1/version 2 - en xsd/boutique.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xsd:annotation>
        <xsd:documentation>
            This scheme captues phone details
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="boutique">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="telephone" type="type-telephone" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="type-telephone">
        <xsd:sequence>
            <xsd:element name="marque" type="xsd:string"/>
            <xsd:element name="modele" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Hamza-Kouki/XML-TPS-/examens/elyessTps/TP1/version 2 - en xsd/boutique.xml
<?xml version="1.0" encoding="UTF-8" ?>

<?xml-stylesheet href="boutique.css" type="text/css"?> 





<boutique xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="boutique.xsd">

	<telephone>
	<marque>Samsung</marque>
	<modele>s10</modele>	
	</telephone>
	
	<telephone>
	<marque>Sony</marque>
	<modele>g5600</modele>	
	</telephone>
	
	<telephone>
	<marque>Nokia</marque>
	<modele>3310</modele>	
	</telephone>


</boutique>
